### PR TITLE
Add support for Swift Package Manager

### LINKED ISSUE #6: missing Package.swift
should be nice to move to Swift Packages

### PR DESCRIPTION
**Pull request by mattt**
Fixes #6

### CODE REVIEW

**Comment by chepiok** [comment]
When I try to add a package dependency I have the error :
https://github.com/NSHipster/ConfettiView.git has no Package.swift manifest for version 0.1.0

**Comment by mattt** [comment]
@chepiok Thanks for taking a look! The reason you're getting that error is that Swift Package Manager isn't in a tagged release yet. Update your `Package.swift` file, replacing the version requirement with `.branch("master")` and try again.

**Comment by mattt** [comment]
@chepiok <ins>Update</ins>: This is now available in 0.2.0. Please disregard my previous advice to target `master` (I'll be renaming that to `main` shortly)

**Comment by chepiok** [comment]
for an unknown reason I have  :

An unknown error occurred. '/Users/xxxxx/Library/Developer/Xcode/DerivedData/Burnout_Watch-addxhwahfbqytqaaspgbejdgxxhe/SourcePackages/checkouts/ConfettiView' exists and is not an empty directory (-4)

Don't understand why. I already tried to delete this directory but it doe not fix the problem. Sorry, I'm a beginner on swift package.

**Pull request merged**
